kind: component
data:
  metrics_sql: |
    SELECT advertiser_name,
      overall_spend,
      total_bids,
      impressions
    FROM
        bids
    ORDER BY
        overall_spend DESC
    LIMIT 10000

vega_lite: |
    {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "repeat": {
        "row": ["overall_spend", "total_bids", "impressions"],
        "column": ["impressions", "total_bids", "overall_spend"]
      },
      "spec": {
        "data": {"name": "table"},
        "mark": "point",
        "params": [
          {
            "name": "brush",
            "select": {
              "type": "interval",
              "resolve": "union",
              "on": "[pointerdown[event.shiftKey], window:pointerup] > window:pointermove!",
              "translate": "[pointerdown[event.shiftKey], window:pointerup] > window:pointermove!",
              "zoom": "wheel![event.shiftKey]"
            }
          },
          {
            "name": "grid",
            "select": {
              "type": "interval",
              "resolve": "global",
              "translate": "[pointerdown[!event.shiftKey], window:pointerup] > window:pointermove!",
              "zoom": "wheel![!event.shiftKey]"
            },
            "bind": "scales"
          }
        ],
        "encoding": {
          "x": {"field": {"repeat": "column"}, "type": "quantitative"},
          "y": {
            "field": {"repeat": "row"},
            "type": "quantitative",
            "axis": {"minExtent": 30}
          },
          "color": {
            "condition": {
              "param": "brush",
              "field": "advertiser_name",
              "type": "nominal"
            },
            "value": "grey"
          }
        }
      }
    }
