kind: component
data:
  metrics_sql: |
    SELECT
    device_type,
    __time as time_grain_hour,
    overall_spend
    FROM
        bids

    ORDER BY
        __time DESC
    LIMIT 200
    OFFSET 0

vega_lite: |
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "description": "Google's stock price over time.",
    "data": {"name": "table"},
    "width": 700,
    "height": 400,
    "mark": {"type": "bar", "width": { "band": 0.75}},
    "encoding": {
      "x": {"field": "time_grain_hour", "type": "temporal", "timeUnit": "monthdatehours"},
      "y": {"field": "overall_spend", "type": "quantitative"},
      "color": {"field": "device_type", "type": "nominal", "legend": null},
      "opacity": {
        "condition": {"param": "hover", "empty": false, "value": 1},
        "value": 0.8
      }
    },
    "params": [{
      "name": "hover",
      "select": {"type": "point", "on": "mouseover"}
    }]
  }


