kind: component
data:
  metrics_sql: |
    SELECT
    player_size,
    __time as time_grain_hour,
    impressions
    FROM
        bids
    ORDER BY
        __time DESC
    LIMIT 200
    OFFSET 0

vega_lite: |
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "description": "Stacked area chart with individual stroke colors for each line and different fill colors",
    "data": {"name": "table"},
    "width": 600,
    "height": 400,
    "layer": [
      {
        "mark": {"type": "area"},
        "encoding": {
          "x": {"field": "time_grain_hour", "type": "temporal"},
          "y": {"field": "impressions", "type": "quantitative", "stack": "zero"},
          "color": {"field": "player_size", "type": "nominal"},
          "opacity": {
            "condition": {"param": "hover", "empty": false, "value": 1},
            "value": 0.8
          }
        },
        "params": [
          {
            "name": "hover",
            "select": {"type": "point", "on": "pointerover"}
          }
        ]
      },
      {
        "mark": {"type": "line", "strokeWidth": 1},
        "encoding": {
          "x": {"field": "time_grain_hour", "type": "temporal"},
          "y": {"field": "impressions", "type": "quantitative", "stack": "zero"},
          "stroke": {"field": "player_size", "type": "nominal"}
        }
      }
    ]
  }
