kind: component
data:
  metrics_sql: |
    SELECT
    __time as time_grain_hour,
    overall_spend
    FROM
        bids
    ORDER BY
        __time DESC
    LIMIT 200
    OFFSET 0


vega_lite: |
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "description": "A bar chart.",
    "width": "container",
    "data": {
      "name": "table"
    },
    "mark": {
      "type": "bar",
      "width": {
        "band": 0.5
      }
    },
    "encoding": {
      "x": {
        "field": "time_grain_hour",
        "type": "temporal",
        "timeUnit": "yearmonthdatehours",
        "axis": {
          "title": ""
        },
        "scale": {
          "domain": [
            "2023-09-16T02:30:00.000Z",
            "2023-09-08T00:00:59.000Z"
          ]
        }
      },
      "y": {
        "field": "overall_spend",
        "type": "quantitative",
        "axis": {
          "title": ""
        }
      },
      "opacity": {
        "condition": {
          "param": "hover",
          "empty": false,
          "value": 1
        },
        "value": 0.8
      }
    },
    "params": [
      {
        "name": "hover",
        "select": {
          "type": "point",
          "on": "pointerover"
        }
      }
    ]
  }