# Chart YAML
# Reference documentation: https://docs.rilldata.com/reference/project-files/charts
    
type: component

data:
  sql: |
    select     
      author_name,
      author_date,
      added_lines,
      deleted_lines,
    from advanced_commits___model
    where author_date > '2024-07-21 00:00:00 Z'
  
    
vega_lite: |
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {"name": "table"},
    "width": "container",
    "height": 400,
    "transform": [
       {
          "calculate": "datum.added_lines / (datum.added_lines + datum.deleted_lines) * 100",
          "as": "percent_added"
        },
        {
          "calculate": "datum.deleted_lines / (datum.added_lines + datum.deleted_lines) * 100",
          "as": "percent_deleted"
        }
          ],


    "layer": [
    {
    "mark": "bar",
    "encoding": {
      "y": {
         "field": "percent_added",
         "type": "quantitative"
        
      },
      "color": {"value": "green"},
      "x": {
        "field": "author_name",
        "type": "nominal",
        "title": "Commit-er Name"
            }
          }
      },
    {
    "mark": "bar",
    "encoding": {
      "y": {
         "field": "percent_deleted",
         "type": "quantitative"
      
      },
      "color": {"value": "red"},
      "x": {
        "field": "author_name",
        "type": "nominal",
        "title": "Commit-er Name"
            }
          }
      }

    ]
  }
  